### ISSUE TITLE
Problems using Intel compilers on Marconi

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-configs#3]
I have failed to get the Intel compilers (either 2018 or 2020 versions) to work on Marconi. The problem seems to be related to linking `libstdc++`. See failed attempts here https://github.com/boutproject/BOUT-configs/tree/marconi-intel-dev.

By default the Intel compilers use the 'system' libstdc++ in /usr/lib. On Marconi this seems to be old, and does not support C++11 features.

Loading the gnu/8.3.0 module helps a bit - compilation errors go away, but I get run-time errors which seem to happen because the executable gets linked to a libstdc++ that sits somewhere inside the `intel/` module (in an `inspector/` subdirectory) which does not have a recent enough version. I tried adding the gnu `lib/` directory at the beginning of `LD_LIBRARY_PATH` and got different run-time errors (`BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES`, with `EXIT CODE: 4`).

I'm not sure what's changed, because I did manage to compile BOUT++ (with a pre-release 4.4 version, https://github.com/boutproject/BOUT-dev/commit/154ebb79b34fb48e583dbf04ba082c664806aa12) previously (early 2021). I had set up modules for that by `source`'ing the following
```
module purge

export LD_LIBRARY_PATH=""

# Intel-2020 versions
module load profile/global profile/advanced profile/candidate env-skl intel/pe-xe-2020--binary intelmpi/2020--binary mkl/2020--binary szip/2.1--gnu--6.1.0 zlib/1.2.8--gnu--6.1.0 hdf5/1.12.0--intel--pe-xe-2020--binary fftw/3.3.8--intelmpi--2020--binary python vtune

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WORK/$USER/intel-versions/pkg/sundials_inst/lib64:$WORK/$USER/intel-versions/pkg/netcdf_inst/lib64/
```

I'm giving up on the Intel compilers now, so leaving this issue in case anyone needs to try again in future.

**Comment by ggeorgakoudis** [comment]
Is this issue relevant anymore?

**Comment by johnomotani** [comment]
> Is this issue relevant anymore?

Unless someone has been successful since this issue was opened in using the Intel compilers on Marconi (I'm not aware of anyone trying...), yes it's still relevant.

**Comment by ggeorgakoudis** [comment]
I'll close this issue for now since there is no one trying it. Feel free to re-open if this is becomes important
